pipeline {
    agent any
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Clean workspace')
        {
            steps
            {
                cleanWs()
            }
        }
        stage('Git clone web deployement') 
        {
            steps 
            {
                dir('Web_dep')
                {
                    git(
                        url: 'https://github.com/birintha/CICD_TP_Deploy_WebApp',
                        credentialsId:'AccountMaster',
                        branch: "${env.GIT_BRANCH}"
                    )
                }
            }
        }
        stage('Destroy web')
        {
            steps
            {
                dir('Web_dep')
                {
                    sh"terraform init -backend-config='path=/home/ubuntu/terraformState/${env.GIT_BRANCH}/web/terraform.tfstate'"
                    sh"terraform destroy -auto-approve -var 'env=${env.GIT_BRANCH}'"
                }
            }
        } 
        stage('Clean Ami')
        {
            steps
            {
                 sh"""
                 export AWS_DEFAULT_REGION='eu-west-1'
                 /var/lib/jenkins/.local/bin/amicleaner --mapping-key name --mapping-values '${env.GIT_BRANCH}' --full-report --keep-previous 0 -f
                 """
            }
        }
        stage('Git clone infra deployement') 
        {
            steps 
            {
                dir('Infra_dep')
                {
                    git(
                        url: 'https://github.com/birintha/CICD_TP_Deploy_Infra',
                        credentialsId:'AccountMaster',
                        branch: "${env.GIT_BRANCH}"
                    )
                }
            }
        }
        stage('Destroy infra')
        {
            steps
            {
                dir('Infra_dep')
                {
                    sh"terraform init -backend-config='path=/home/ubuntu/terraformState/${env.GIT_BRANCH}/infra/terraform.tfstate'"
                    sh"terraform destroy -auto-approve -var 'env=${env.GIT_BRANCH}' "
                }
            }
        }
    }
}